name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v2
      - uses: Swatinem/rust-cache@v2
      - run: cargo install --verbose --git https://github.com/aiken-lang/aiken.git
      - run: aiken fmt --check
      - run: aiken check -D
      - run: aiken docs -o docs
      - uses: actions/upload-pages-artifact@v2
        with:
          path: "docs/"

  publish-documentation:
    # Uncomment when stable.
    #
    # if: ${{ startsWith(github.ref, 'refs/tags') }}
    if: ${{ github.event_name == 'push' }}
    needs: check
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
